# Generated by Django 3.1.7 on 2021-10-18 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=128)),
                ('date', models.DateTimeField(auto_now=True)),
                ('query', models.CharField(max_length=1024)),
                ('author', models.ForeignKey(blank=True, db_column='author', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Queries',
                'db_table': 'query',
            },
        ),
        migrations.AddConstraint(
            model_name='query',
            constraint=models.UniqueConstraint(fields=('name',), name='query_name'),
        ),
    ]
