# Generated by Django 3.1.7 on 2021-10-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
