# Generated by Django 3.1.7 on 2021-12-12 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboards', '0002_auto_20211018_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='author',
            field=models.ForeignKey(blank=True, db_column='author', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
