# Generated by Django 3.1.7 on 2022-01-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0008_dashboard_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
