# Generated by Django 3.1.7 on 2022-01-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0010_layout_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layout',
            name='temp',
        ),
    ]
