# Generated by Django 3.1.7 on 2022-03-01 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboards', '0011_remove_layout_temp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='component',
            table='dash_component',
        ),
        migrations.AlterModelTable(
            name='dashboard',
            table='dash_dashboard',
        ),
        migrations.AlterModelTable(
            name='layout',
            table='dash_layout',
        ),
        migrations.AlterModelTable(
            name='query',
            table='dash_query',
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, db_column='author', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_author', to=settings.AUTH_USER_MODEL)),
                ('layout', models.ForeignKey(blank=True, db_column='layout', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_layout', to='dashboards.layout')),
            ],
            options={
                'verbose_name_plural': 'Config',
                'db_table': 'dash_config',
            },
        ),
    ]
