# Generated by Django 3.1.7 on 2022-03-01 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0012_auto_20220301_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='layout',
        ),
        migrations.AddField(
            model_name='config',
            name='dashboard',
            field=models.ForeignKey(blank=True, db_column='dashboard', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_dashboard', to='dashboards.layout'),
        ),
    ]
