# Generated by Django 3.1.7 on 2022-03-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0015_component_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='date_format',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
