# Generated by Django 3.1.7 on 2022-06-06 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0017_auto_20220606_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshot',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='snapshot',
            name='title',
        ),
    ]
