# Generated by Django 3.1.7 on 2022-06-21 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0019_auto_20220606_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='layout',
            field=models.ForeignKey(blank=True, db_column='layout', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot_layout', to='dashboards.layout'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
